services:
  backend:
    image: ghcr.io/maximshmelyov/client-dashboard-back/backend:latest
    container_name: client-dashboard-backend-api
    restart: always
    env_file: .env.local.docker
    depends_on:
      - postgres
      - mongo
      - redis
    networks:
      - client-dashboard-backend-network
